add wave sim:/u1/*
add wave sim:/u1/b1/ERROR_FIFO_RESET_SHOULD_CAUSE_EMPTY1_FULL0_RPTR0_WPTR0_CNT0
add wave sim:/u1/b1/ERROR_FIFO_SHOULD_BE_FULL
add wave sim:/u1/b1/ERROR_FIFO_SHOULD_NOT_BE_FULL
add wave sim:/u1/b1/ERROR_FIFO_DID_NOT_GO_FULL
add wave sim:/u1/b1/ERROR_FIFO_SHOULD_BE_EMPTY
add wave sim:/u1/b1/ERROR_FIFO_SHOULD_NOT_BE_EMPTY
add wave sim:/u1/b1/ERROR_FIFO_DID_NOT_GO_EMPTY
add wave sim:/u1/b1/ERROR_FIFO_FULL_WRITE_CAUSED_WPTR_TO_CHANGE
add wave sim:/u1/b1/ERROR_FIFO_FULL_WRITE_CAUSED_FULL_FLAG_TO_CHANGE
add wave sim:/u1/b1/ERROR_FIFO_EMPTY_READ_CAUSED_EMPTY_FLAG_TO_CHANGE
add wave sim:/u1/b1/ERROR_FIFO_EMPTY_READ_CAUSED_RPTR_TO_CHANGE
add wave sim:/u1/b1/ERROR_FIFO_WORD_COUNTER_IS_NEGATIVE
add wave sim:/u1/b1/ERROR_FIFO_READWRITE_ILLEGAL_FIFO_FULL_OR_EMPTY

